print("Hello World!.")
print("Welcome to Python.")
print("Amrutha Sai Bathula")
print("I am learning Python.")
print("Python Programming.")
print("Good Morning.")
print("Welcome Students.")
print("Python is easy.")
print("My First Program.")
print("Hello from Python!.")